version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=devDB
      - DB_USER=devUser
      - DB_PASS=Changemedude
    command: >
      sh -c "python manage.py await_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: "postgres:13-alpine3.19"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devDB
      - POSTGRES_USER=devUser
      - POSTGRES_PASSWORD=Changemedude

volumes:
  dev-db-data:
