# Generated by Django 4.2.8 on 2024-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_alter_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(default=[], related_name='entries', to='core.tag'),
        ),
    ]
