# Generated by Django 4.2.8 on 2024-04-16 14:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=core.models.upload_file_location),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='16 April, 2024', max_length=255),
        ),
    ]
