---
name: Checks And Validation

on: [push]

jobs:
  test-lint-and-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py await_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
      - name: Validation
        run: docker compose run --rm app sh -c "mypy @type_check_list"